### ISSUE TITLE
Vanadium cannot communicate with sandboxed Google Play Services

### ISSUE THREAD

**Issue by hmenke** [GrapheneOS/Vanadium#129]
When visiting https://paypal.com/ and selecting login Vanadium crashes.

This attempts to use a fido2 token but it looks like the intent is malformed.

I believe this is the relevant excerpt from logcat:

```
10-29 18:04:48.683 21914 21914 D Zygote  : Forked child process 22279
10-29 18:04:48.685 22279 22279 E libc    : SetHeapTaggingLevel: re-enabling tagging after it was disabled is not supported
10-29 18:04:48.690  1542  1760 I ActivityManager: Start proc 22279:org.robotnix.vanadium:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:6/u0ai6 for  {org.robotnix.vanadium/org.chromium.content.app.SandboxedProcessService0:6}
10-29 18:04:48.711 22279 22279 E ocessService0:: Not starting debugger since process cannot load the jdwp agent.
10-29 18:04:48.857 21860 21860 I cr_tabmodel: Appending tabs being restored to metadata lists, 0, startingNormalCount: 1, startingIncognitoCount: 1
10-29 18:04:48.857 21860 21860 I cr_tabmodel: Serializing tab lists; counts: 1, 1
10-29 18:04:48.898 13032 13032 D GmsCompat/Hooks: Posting notification for service: com.google.android.gms.chimera.GmsBoundBrokerService
10-29 18:04:48.905 13032 13032 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.fido.fido2.privileged.START pkg=com.google.android.gms }
10-29 18:04:48.905 13032 13032 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.fido.fido2.privileged.START pkg=com.google.android.gms }
10-29 18:04:48.949 13032 13544 W PermCheckPreProcessor: API 149 requires missing permission groups: [android.permission-group.STORAGE]
10-29 18:04:48.957 21860 22295 E AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
10-29 18:04:48.957 21860 22295 E AndroidRuntime: Process: org.robotnix.vanadium, PID: 21860
10-29 18:04:48.957 21860 22295 E AndroidRuntime: java.lang.IllegalArgumentException: org.robotnix.vanadium: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
10-29 18:04:48.957 21860 22295 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at Rl0.b(chromium-ChromeModernPublic.aab-stable-463805015:13)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at Ol0.e(chromium-ChromeModernPublic.aab-stable-463805015:41)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at Ol0.f0(chromium-ChromeModernPublic.aab-stable-463805015:1)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at gp.a(chromium-ChromeModernPublic.aab-stable-463805015:3)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at cp.b(chromium-ChromeModernPublic.aab-stable-463805015:11)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at dp.handleMessage(chromium-ChromeModernPublic.aab-stable-463805015:53)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
10-29 18:04:48.957 21860 22295 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

I've compiled GrapheneOS 2021102613 from source using the [robotnix](https://github.com/danielfullmer/robotnix/) build system.

Please let me know if you need more information.

**Comment by hmenke** [comment]
Fixed in GrapheneOS 2021110617. Thank you very much.
