### ISSUE TITLE
Vanadium crashing

### ISSUE THREAD

**Issue by duggalsu** [GrapheneOS/Vanadium#436]
Here is the stack trace

```
type: crash
osVersion: google/sunfish/sunfish:13/TQ3A.230805.001.S1/2024010700:user/release-keys
package: org.chromium.chrome:616710234
process: app.vanadium.browser
processUptime: 42830 + 722 ms
installer: app.grapheneos.apps

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.chromium.chrome/org.chromium.chrome.browser.ChromeTabbedActivity}: android.view.InflateException: Binary XML file line #29 in app.vanadium.browser:layout/main: Binary XML file line #13 in app.vanadium.browser:layout/compositor_view_holder: Error inflating class org.chromium.chrome.browser.compositor.CompositorViewHolder
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3655)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.view.InflateException: Binary XML file line #29 in app.vanadium.browser:layout/main: Binary XML file line #13 in app.vanadium.browser:layout/compositor_view_holder: Error inflating class org.chromium.chrome.browser.compositor.CompositorViewHolder
Caused by: android.view.InflateException: Binary XML file line #13 in app.vanadium.browser:layout/compositor_view_holder: Error inflating class org.chromium.chrome.browser.compositor.CompositorViewHolder
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1235)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at L9.j(chromium-TrichromeChrome64.apk-stable-616710234:24)
	at m9.setContentView(chromium-TrichromeChrome64.apk-stable-616710234:2)
	at Tv.setContentView(chromium-TrichromeChrome64.apk-stable-616710234:9)
	at zv.C1(chromium-TrichromeChrome64.apk-stable-616710234:56)
	at zv.q1(chromium-TrichromeChrome64.apk-stable-616710234:163)
	at Jc.V(chromium-TrichromeChrome64.apk-stable-616710234:38)
	at lw.c(chromium-TrichromeChrome64.apk-stable-616710234:64)
	at Jc.onCreate(chromium-TrichromeChrome64.apk-stable-616710234:196)
	at android.app.Activity.performCreate(Activity.java:8389)
	at android.app.Activity.performCreate(Activity.java:8368)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1422)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3636)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.IllegalArgumentException: SemanticColorUtils requires a value for the app.vanadium.browser:attr/colorSurface attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).
	at lA0.b(chromium-TrichromeChrome64.apk-stable-616710234:41)
	at ao1.a(chromium-TrichromeChrome64.apk-stable-616710234:6)
	at qw.b(chromium-TrichromeChrome64.apk-stable-616710234:11)
	at org.chromium.chrome.browser.compositor.CompositorView.b(chromium-TrichromeChrome64.apk-stable-616710234:23)
	at org.chromium.chrome.browser.compositor.CompositorView.<init>(chromium-TrichromeChrome64.apk-stable-616710234:16)
	at org.chromium.chrome.browser.compositor.CompositorViewHolder.<init>(chromium-TrichromeChrome64.apk-stable-616710234:112)
	... 39 more

```

**Comment by duggalsu** [comment]
Simply launching the browser. It's not opening

**Comment by duggalsu** [comment]
yes

**Comment by duggalsu** [comment]
Just checked that the last update was 2 days ago. So, it didn't cause issues after the first reboot yesterday. The issue started happening after the second reboot today. It's happening across all profiles, including owner profile

**Comment by duggalsu** [comment]
Uninstalling and re-installing the updates worked. Closing issue
