### ISSUE TITLE
Vanadium crashes upon opening

### ISSUE THREAD

**Issue by CodeShakingSheep** [GrapheneOS/Vanadium#437]
This happens after the latest release. If I open Vanadium it immediately closes and is currently unusable on both of my profiles. Here is the relevant log part.

```
--------- switch to crash
1706517141.796  3085  3085 E AndroidRuntime: FATAL EXCEPTION: main
1706517141.796  3085  3085 E AndroidRuntime: Process: app.vanadium.browser, PID: 3085
1706517141.796  3085  3085 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.chromium.chrome/org.chromium.chrome.browser.ChromeTabbedActivity}: android.view.InflateException: Binary XML file line #29 in app.vanadium.browser:layout/main: Binary XML file line #13 in app.vanadium.browser:layout/compositor_view_holder: Error inflating class org.chromium.chrome.browser.compositor.CompositorViewHolder
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3833)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3974)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8279)
1706517141.796  3085  3085 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
1706517141.796  3085  3085 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
1706517141.796  3085  3085 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
1706517141.796  3085  3085 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
1706517141.796  3085  3085 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
1706517141.796  3085  3085 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #29 in app.vanadium.browser:layout/main: Binary XML file line #13 in app.vanadium.browser:layout/compositor_view_holder: Error inflating class org.chromium.chrome.browser.compositor.CompositorViewHolder
1706517141.796  3085  3085 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #13 in app.vanadium.browser:layout/compositor_view_holder: Error inflating class org.chromium.chrome.browser.compositor.CompositorViewHolder
1706517141.796  3085  3085 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
1706517141.796  3085  3085 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
1706517141.796  3085  3085 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:866)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1135)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1243)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:664)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
1706517141.796  3085  3085 E AndroidRuntime: 	at L9.j(chromium-TrichromeChrome6432.apk-stable-616710332:24)
1706517141.796  3085  3085 E AndroidRuntime: 	at m9.setContentView(chromium-TrichromeChrome6432.apk-stable-616710332:2)
1706517141.796  3085  3085 E AndroidRuntime: 	at Tv.setContentView(chromium-TrichromeChrome6432.apk-stable-616710332:9)
1706517141.796  3085  3085 E AndroidRuntime: 	at zv.C1(chromium-TrichromeChrome6432.apk-stable-616710332:56)
1706517141.796  3085  3085 E AndroidRuntime: 	at zv.q1(chromium-TrichromeChrome6432.apk-stable-616710332:163)
1706517141.796  3085  3085 E AndroidRuntime: 	at Jc.V(chromium-TrichromeChrome6432.apk-stable-616710332:38)
1706517141.796  3085  3085 E AndroidRuntime: 	at lw.c(chromium-TrichromeChrome6432.apk-stable-616710332:64)
1706517141.796  3085  3085 E AndroidRuntime: 	at Jc.onCreate(chromium-TrichromeChrome6432.apk-stable-616710332:196)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8674)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8652)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1461)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3974)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
1706517141.796  3085  3085 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8279)
1706517141.796  3085  3085 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
1706517141.796  3085  3085 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
1706517141.796  3085  3085 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
1706517141.796  3085  3085 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
1706517141.796  3085  3085 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
1706517141.796  3085  3085 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: SemanticColorUtils requires a value for the app.vanadium.browser:attr/colorSurface attribute to be set in your app theme. You can either set the attribute in your theme or update your theme to inherit from Theme.MaterialComponents (or a descendant).
1706517141.796  3085  3085 E AndroidRuntime: 	at lA0.b(chromium-TrichromeChrome6432.apk-stable-616710332:41)
1706517141.796  3085  3085 E AndroidRuntime: 	at ao1.a(chromium-TrichromeChrome6432.apk-stable-616710332:6)
1706517141.796  3085  3085 E AndroidRuntime: 	at qw.b(chromium-TrichromeChrome6432.apk-stable-616710332:11)
1706517141.796  3085  3085 E AndroidRuntime: 	at org.chromium.chrome.browser.compositor.CompositorView.b(chromium-TrichromeChrome6432.apk-stable-616710332:23)
1706517141.796  3085  3085 E AndroidRuntime: 	at org.chromium.chrome.browser.compositor.CompositorView.<init>(chromium-TrichromeChrome6432.apk-stable-616710332:16)
1706517141.796  3085  3085 E AndroidRuntime: 	at org.chromium.chrome.browser.compositor.CompositorViewHolder.<init>(chromium-TrichromeChrome6432.apk-stable-616710332:112)
1706517141.796  3085  3085 E AndroidRuntime: 	... 39 more
```

**Comment by pabloscloud** [comment]
Same for me

**Comment by saroman2** [comment]
Happening here as well
