### ISSUE TITLE
WebAssembly is not defined

### ISSUE THREAD

**Issue by Mrestof** [GrapheneOS/Vanadium#603]
I am trying to run the game made in [LÖVE](https://www.love2d.org/) game engine and packaged for web with [love.js](https://github.com/Davidobot/love.js), it uses WebAssembly to run in browser. I tried to run the game in Chrome and it launches well, but not in Vanadium. I am far from technical details, but I used Eruda to get the following logs.

first log msg in console:
```
no native wasm support detected

at t.value (http://192.168.1.199:8000/node_modules/eruda/eruda.js:2:17465)
at new t (http://192.168.1.199:8000/node_modules/eruda/eruda.js:2:12630)
at t.value (http://192.168.1.199:8000/node_modules/eruda/eruda.js:2:32766)
at http://192.168.1.199:8000/node_modules/eruda/eruda.js:2:34400
```

second log msg in console:
```
WebAssembly is not defined

at abort (http://192.168.1.199:8000/love.js:9:15270)
at http://192.168.1.199:8000/love.js:9:6840
at applicationLoad (http://192.168.1.199:8000/:104:9)
at HTMLScriptElement.onload (http://192.168.1.199:8000/:108:87)

```

**Comment by Mrestof** [comment]
Oh, right. Went straight to github issues, didn't look on forums. Now it works, thanks!
